# Note: It requires docker-compose 1.17.1
#
# Usage: docker-compose up -d
version: "3.0"

services:
  nexus_7.1.1:
    container_name: emulator
    image: jaggernod/emulator:0.41
    privileged: true
    ports:
      - "5554:5554"
      - "5555:5555"
    environment:
      - DEVICE=Nexus 6
      - SKIP_AVD_CREATION=False

